/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#c2c6d6",
        "on-secondary-fixed-variant": "#5516be",
        "tertiary": "#89ceff",
        "on-primary": "#002e6a",
        "tertiary-container": "#009ada",
        "secondary": "#d0bcff",
        "on-tertiary": "#00344d",
        "on-secondary-fixed": "#23005c",
        "on-secondary": "#3c0091",
        "surface-bright": "#33394c",
        "primary": "#adc6ff",
        "outline": "#8c909f",
        "surface-container-low": "#151b2d",
        "surface-variant": "#2e3447",
        "inverse-primary": "#005ac2",
        "on-tertiary-container": "#002d43",
        "tertiary-fixed-dim": "#89ceff",
        "surface-container-high": "#23293c",
        "on-background": "#dce1fb",
        "outline-variant": "#424754",
        "secondary-container": "#571bc1",
        "tertiary-fixed": "#c9e6ff",
        "secondary-fixed": "#e9ddff",
        "on-tertiary-fixed-variant": "#004c6e",
        "surface": "#0c1324",
        "secondary-fixed-dim": "#d0bcff",
        "primary-fixed-dim": "#adc6ff",
        "error-container": "#93000a",
        "on-primary-fixed": "#001a42",
        "surface-container-highest": "#2e3447",
        "inverse-on-surface": "#2a3043",
        "on-tertiary-fixed": "#001e2f",
        "on-primary-fixed-variant": "#004395",
        "on-primary-container": "#00285d",
        "surface-container-lowest": "#070d1f",
        "primary-container": "#4d8eff",
        "background": "#0c1324",
        "on-secondary-container": "#c4abff",
        "primary-fixed": "#d8e2ff",
        "on-surface": "#dce1fb",
        "inverse-surface": "#dce1fb",
        "on-error-container": "#ffdad6",
        "surface-dim": "#0c1324",
        "on-error": "#690005",
        "surface-tint": "#adc6ff",
        "surface-container": "#191f31",
        "error": "#ffb4ab"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "gutter": "24px",
        "margin-desktop": "80px",
        "unit": "4px",
        "margin-mobile": "20px",
        "margin-tablet": "40px",
        "container-max": "1440px"
      },
      fontFamily: {
        "label-md": ["JetBrains Mono", "monospace"],
        "body-md": ["Geist", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Geist", "sans-serif"],
        "display-lg-mobile": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "headline-xl": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
